server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://114.116.106.206:3306/library?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: admin_SQL_&23G%s3
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.southwind.entity
logging:
  level:
    com.southwind.repository.*: debug